# Generated by Django 6.1 on 2026-09-01 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(help_text='e.g. it-quiz', max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=100)),
                ('format_type', models.CharField(help_text='Individual or Team', max_length=50)),
                ('team_size', models.IntegerField(default=1)),
                ('venue', models.CharField(max_length=150)),
                ('time', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Competition Track',
                'verbose_name_plural': 'Competition Tracks (14 Events)',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_id', models.CharField(help_text='e.g. INS-2026-8491', max_length=50, unique=True)),
                ('event_name', models.CharField(max_length=150)),
                ('squad_name', models.CharField(max_length=150)),
                ('team_name', models.CharField(blank=True, max_length=200, null=True)),
                ('participants', models.TextField(help_text='Comma-separated participant delegate names')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('year', models.CharField(max_length=50)),
                ('course', models.CharField(default='BCA', max_length=100)),
                ('section', models.CharField(max_length=50)),
                ('roll_no', models.CharField(max_length=50)),
                ('venue', models.CharField(blank=True, max_length=150, null=True)),
                ('time', models.CharField(blank=True, max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Delegate Registration',
                'verbose_name_plural': 'Delegate Registrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('squad_id', models.CharField(help_text='e.g. team_01', max_length=50, unique=True)),
                ('num', models.CharField(help_text='e.g. Team 01', max_length=50)),
                ('name', models.CharField(help_text='e.g. TEAM CHRONIX', max_length=150, unique=True)),
                ('captain', models.CharField(blank=True, max_length=150)),
                ('vice_captain', models.CharField(blank=True, max_length=150)),
                ('points', models.IntegerField(default=0, help_text='Total accumulated points')),
                ('badge_color', models.CharField(default='#10B981', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Squad Score',
                'verbose_name_plural': 'Squad Scores (11 Teams)',
                'ordering': ['-points', 'squad_id'],
            },
        ),
        migrations.CreateModel(
            name='ScoreAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta_points', models.IntegerField(help_text='Points added or subtracted')),
                ('resulting_points', models.IntegerField(help_text='Score after modification')),
                ('event_name', models.CharField(blank=True, max_length=150, null=True)),
                ('allocated_by', models.CharField(default='admin', max_length=100)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_logs', to='api.squad')),
            ],
            options={
                'verbose_name': 'Score Audit Log',
                'verbose_name_plural': 'Score Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
